server:
  port: 80


spring:
  security:
    user:
      name: user
      password: 1234

  thymeleaf:
    cache: false


  # 파일 크기 제한
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-file-size: 100MB
      max-request-size: 100MB

#  h2:
#    console:
#      enabled: true
#      path: /h2

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lms_project
    username: root
    password: mariadb

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

